// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/auth': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/auth').default>>>>
    }
    '/chat': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/chat').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@3.20.0_db0@0.3.4_ioredis@5.8.2_magicast@0.5.0_nuxt@3.20.0_@parcel+wa_a051a755c843d01a48093f59c58deeb7/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+icon@1.15.0_magicast@0.5.0_vite@7.1.12_@types+node@20.19.24_jiti@2.6.1_terser@5.4_a6fdd227e2ec67bb0dc4922b476f6a50/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}